apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: si3mshady/doggone-frontend:v1
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://thecloudshepherd.sreuniversity.org:5000/upload"

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: si3mshady/doggone-backend:v1
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: access-key
        - name: NODE_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: secret-access-key
---        
apiVersion: v1
  kind: Secret
  metadata:
    name: backend-secrets
  type: Opaque
  data:
    access-key: QUtJQVU0QVc3WENXU0VQS1NKV1Q=
    secret-access-key: dGZNVWJ3QURad01SV3hDbHZOODFUMXF3cENzQWlwVkJiT0MyMUpoeg==




