name: List S3 Buckets

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Kubernetes Cluster
        run: |
          aws ssm send-command \
          --instance-ids "i-04efd57bb229490cb" \
          --document-name "AWS-RunShellScript" \
          --parameters '{"commands":["kubectl apply -f k8s.yml"]}'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1