name: Build and Deploy Kubernetes Application

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
        if: ${{ github.ref == 'refs/heads/main' }}

      # - name: Install AWS CLI
      #   run: |
      #     # Install AWS CLI
      #     curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip awscliv2.zip
      #     sudo ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
      #   if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}

      - name: Build and Test
        run: |
          # Add your build and test commands here
          echo "Building and testing..."
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}

      - name: Deploy to Kubernetes Cluster
        run: |
          # Use SSM to run kubectl commands on the Kubernetes cluster
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          # echo "done"
          aws ssm send-command --instance-ids "i-08abce791aa7d7ada" --document-name "AWS-RunShellScript" --parameters '{"commands":["kubectl apply -f k8s.yml"]}'
        if: ${{ github.ref == 'refs/heads/main' }}

      # - name: Push to Docker Hub
      #   run: |
      #     # Push your Docker image to Docker Hub
      #     docker build -t si3mshady/doggone:latest .
      #     docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      #     docker push si3mshady/doggone:latest
      #   if: ${{ github.ref == 'refs/heads/dev' }}
